const recipes = [
  {
    "name": "Flemmenkueche",
    "lowerCaseName": "flemmenkueche",
    "key": 1,
    "ingredients": [
      [1, "pâte à pizza"],
      [1, "pâte feuilletée"],
      [150, "gr lardons"],
      [2, "gros oignons"],
      [20, "cl crème liquide"],
      ["Poivre"],
      ["Sel"],
      ["Muscade"],
    ],
    "basePersonsIngredients": 2,
    "recipe": [
      "Préchauffer le four selon les instructions de cuisson de la pâte",
      "Mettre la pâte dans le moule en laissant le papier de cuisson",
      "Piquer la pâte",
      "Laméliser les oignons",
      "Répartir les oignons lamélisés et les lardons sur la pâte",
      "Ajouter la crème (ne pas forcément tout mettre, moins peut suffire)",
      "Saler poivrer muscader",
      "Enfourner selon les instructions de cuisson",
      "Accompagnement recommandé : salade",
    ],
    "temperature": "Chaud",
    "isVegetarian": false,
    "isQuick": true,
    "isTuppable": false,
  },
  {
    name: "Soupe déglincoco",
    lowerCaseName: "soupedeglincoco",
    key: 2,
    ingredients: [
      [1, "patate douce"],
      [1, "poireau ou oignon"],
      [1, "petite carotte"],
      [20, "cl crème de coco"],
      ["Epices"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Mettre les légumes coupés dans l'appareil à soupe",
      "Ajouter un cube de bouillon de volaille",
      "Ajouter la crème de coco",
      "Ajouter de l'eau",
      "Assaisonner (sel - poivre - muscade - piment)",
      "Lancer le programme soupe",
    ],
    temperature: "Chaud",
    isVegetarian: true,
    isQuick: true,
    isTuppable: false,
  },
  {
    name: "Pâtes aux poireaux et crevettes",
    lowerCaseName: "patespoireauxcrevettes",
    key: 3,
    ingredients: [
      [200, "gr pâtes complètes"],
      [2, "poireaux"],
      [10, "crevettes"],
      [20, "cl crème liquide"],
      ["Beurre"],
      ["Poivre"],
      ["Sel"],
      ["Muscade"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Couper les poireaux",
      "Faire revenir les poireaux feu moyen dans du beurre 10/15mn",
      "Mettre les pâtes à cuire",
      "Ajouter les crevettes dans la poêle",
      "Ajouter la crème",
      "Assaisonner",
    ],
    temperature: "Chaud",
    isVegetarian: false,
    isQuick: false,
    isTuppable: true,
  },
];

module.exports = { recipes };
