const recipes = [
  {
    name: "Flemmenkueche",
    lowerCaseName: "flemmenkueche",
    key: 1,
    ingredients: [
      [1, "pâte à pizza"],
      [1, "pâte feuilletée"],
      [150, "gr lardons"],
      [2, "gros oignons"],
      [20, "cl crème liquide"],
      ["Poivre"],
      ["Sel"],
      ["Muscade"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Préchauffer le four selon les instructions de cuisson de la pâte",
      "Mettre la pâte dans le moule en laissant le papier de cuisson",
      "Piquer la pâte",
      "Laméliser les oignons",
      "Répartir les oignons lamélisés et les lardons sur la pâte",
      "Ajouter la crème (ne pas forcément tout mettre, moins peut suffire)",
      "Saler poivrer muscader",
      "Enfourner selon les instructions de cuisson",
      "Accompagnement recommandé : salade",
    ],
    temperature: "Chaud",
    isVegetarian: false,
    isQuick: false,
    isTuppable: false,
  },
  {
    name: "Soupe déglincoco",
    lowerCaseName: "soupedeglincoco",
    key: 2,
    ingredients: [
      [1, "patate douce"],
      [1, "poireau ou oignon"],
      [1, "petite carotte"],
      [20, "cl crème de coco"],
      ["Epices"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Mettre les légumes coupés dans l'appareil à soupe",
      "Ajouter un cube de bouillon de volaille",
      "Ajouter la crème de coco",
      "Ajouter de l'eau",
      "Assaisonner (sel - poivre - muscade - piment)",
      "Lancer le programme soupe",
    ],
    temperature: "Chaud",
    isVegetarian: true,
    isQuick: true,
    isTuppable: false,
  },
  {
    name: "Pâtes aux poireaux et crevettes",
    lowerCaseName: "patespoireauxcrevettes",
    key: 3,
    ingredients: [
      [200, "gr pâtes complètes"],
      [2, "poireaux"],
      [10, "crevettes"],
      [20, "cl crème liquide"],
      ["Beurre"],
      ["Poivre"],
      ["Sel"],
      ["Muscade"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Couper les poireaux",
      "Faire revenir les poireaux feu moyen dans du beurre 10/15mn",
      "Mettre les pâtes à cuire",
      "Ajouter les crevettes dans la poêle",
      "Ajouter la crème",
      "Assaisonner",
    ],
    temperature: "Chaud",
    isVegetarian: false,
    isQuick: false,
    isTuppable: true,
  },
  {
    name: "Riz cantonnais",
    lowerCaseName: "rizcantonnais",
    key: 4,
    ingredients: [
      [120, "gr de riz thaï (ou basmati)"],
      [1, "oignon"],
      [2, "oeufs"],
      ["Petits pois"],
      ["Jambon ou lardons"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Battre les oeufs et faire une omelette bien cuite - réserver",
      "Emincer l'oignon et le cuire",
      "Mettre à cuire le riz",
      "Ajouter les lardons ou le jambon découpé",
      "Ajouter les petits pois",
      "Egoutter et ajouter le riz",
      "Assaisonner",
    ],
    isVegetarian: false,
    isQuick: false,
    isTuppable: true,
  },
  {
    name: "Chili con carne",
    lowerCaseName: "chiliconcarne",
    key: 5,
    ingredients: [
      [50, "g de beurre"],
      [2, "oignons"],
      [2, "gousses d'ail écrasées"],
      [1, "c.à.c. chili en poudre"],
      [2, "c.à.c. cumin en poudre"],
      [65, "g de concentré de tomates"],
      [1, "grosse boîte de haricots rouges"],
      [30, "cl de bouillon de boeuf"],
      [500, "g boeuf hâché"],
      ["sel"],
      ["poivre"],
    ],
    basePersonsIngredients: 4,
    recipe: [
      "Préchauffer le four à 180°C (thermostat 6).",
      "Hacher l'oignon et l'ail.",
      "Faire fondre le beurre, et ensuite dorer doucement l'oignon et l’ail.",
      "Incorporer le boeuf haché et laisser cuire doucement 10 min.",
      "Mélanger le chili, le cumin, le concentré de tomates, et incorporer le tout au boeuf. Ajouter les haricots, le bouillon, du sel et du poivre.",
    ],
    isVegetarian: false,
    isQuick: false,
    isTuppable: true,
  },
  {
    name: "Penne all'Arrabbiata",
    lowerCaseName: "penneall'arrabbiata",
    key: 6,
    ingredients: [
      [400, "gr de penne"],
      [3, "gousses d'ail"],
      [400, "gr de pulpe de tomates"],
      [1, "cs piment de cayenne"],
      ["Laurier ou thym"],
      ["Parmesan"],
    ],
    basePersonsIngredients: 4,
    recipe: [
      "Hacher les gousses d'ail",
      "Faire revenir l'ail avec de l'huile",
      "Ajouter la pulpe de tomates, le piment, le laurier ou thym",
      "Mélanger et faire mijoter 15mn",
      "En parallèle faire cuire les pâtes al dente",
      "Egoutter les pâtes",
      "Melanger les pâtes et la sauce, laisser imbiber",
      "Servir avec du parmesan",
    ],
    isVegetarian: true,
    isQuick: true,
    isTuppable: true,
  },
  {
    name: "Pâtes au chorizo",
    lowerCaseName: "pâtesauchorizo",
    key: 7,
    ingredients: [
      ["Une plaquette de chorizo"],
      [1, "oignon rouge"],
      [200, "gr pâtes complètes"],
      [20, "cl crème liquide"],
    ],
    basePersonsIngredients: 2,
    recipe: [
      "Lameliser les oignons",
      "Cuire les oignons",
      "Ajouter le chorizo découpé",
      "Ajouter la crème",
      "Servir avec les pâtes",
    ],
    isVegetarian: false,
    isQuick: false,
    isTuppable: true,
  },
];

module.exports = { recipes };
